// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuuQBY-oktLkfi3q6T7RwL4q_XsBJ-K3k',
    appId: '1:913993722547:web:e90b28d36ee32a4be45ec6',
    messagingSenderId: '913993722547',
    projectId: 'billk1',
    authDomain: 'billk1.firebaseapp.com',
    storageBucket: 'billk1.firebasestorage.app',
    measurementId: 'G-M4V2210K36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wgSsoqB5Xy46oZdpJmNJC9hoXj0hKFw',
    appId: '1:913993722547:android:2e8ed2accc5dfe3ae45ec6',
    messagingSenderId: '913993722547',
    projectId: 'billk1',
    storageBucket: 'billk1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJAJ0FsxhIraZ_gecUF_Y-KBuY3IzjHcg',
    appId: '1:913993722547:ios:3a6b7fc90ec147a2e45ec6',
    messagingSenderId: '913993722547',
    projectId: 'billk1',
    storageBucket: 'billk1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJAJ0FsxhIraZ_gecUF_Y-KBuY3IzjHcg',
    appId: '1:913993722547:ios:3a6b7fc90ec147a2e45ec6',
    messagingSenderId: '913993722547',
    projectId: 'billk1',
    storageBucket: 'billk1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuuQBY-oktLkfi3q6T7RwL4q_XsBJ-K3k',
    appId: '1:913993722547:web:727b87f3477174eee45ec6',
    messagingSenderId: '913993722547',
    projectId: 'billk1',
    authDomain: 'billk1.firebaseapp.com',
    storageBucket: 'billk1.firebasestorage.app',
    measurementId: 'G-0E6GF2L7FN',
  );
}
